"""The Compliance Passport as a DOCUMENT (P2 §12).

The owner's verdict on the previous output was "looks AI-generated, not like a
professional company document — no branding, no verification signature, no
stamps". test_passport.py already covers the data window and the coverage
figures; this file covers the things that make it an artefact somebody is willing
to hand to an auditor, and the two traps in doing so:

  · The response is a PDF, so the document's HTML is never on the wire. It is
    CAPTURED from the renderer's input instead (see `_html`), which keeps every
    assertion below pointed at the real template output assembled by the real
    route. There used to be an HTML degrade to read it from; that was removed
    because a caller asking for a PDF must not be handed HTML under a 200.
  · Page numbering is a @page counter that only takes effect in the PDF, so it is
    asserted as a declaration in the CSS rather than as rendered text.

Above all §12.6: this is evidence. Every figure traces to a passport.py counter.
"""

from __future__ import annotations

import base64
import hashlib
import re
import sys
import uuid
from pathlib import Path

import pytest
from sqlalchemy import text

from app.db import SessionLocal

_h = lambda s: hashlib.sha256(s.encode()).hexdigest()  # noqa: E731


def _ingest(client, org, n, tag="chat"):
    payload = [{"prompt_hash": _h(f"p{i}"), "response_hash": _h(f"r{i}"),
                "token_count": 10 + i, "policy_tag": tag} for i in range(n)]
    assert client.post("/v1/logs/batch", headers=org["auth"], json=payload).status_code == 202


def _flat(doc: str) -> str:
    """Collapse whitespace so a PROSE assertion does not depend on where the
    template happens to wrap a line. Markup assertions still use the raw text."""
    return re.sub(r"\s+", " ", doc)


def _stub_renderer(monkeypatch) -> dict:
    """Install a weasyprint stand-in that RECORDS the html it is handed.

    The route returns a PDF and nothing else, so this is how the document's HTML
    is inspected — from the renderer's input rather than from a response body.
    It exercises the real context assembly; only the native rendering is faked."""
    captured: dict = {}

    class _FakeHTML:
        def __init__(self, string=None, **kw):
            captured["html"] = string

        def write_pdf(self):
            return b"%PDF-1.7\nstub\n%%EOF"

    fake = type(sys)("weasyprint")
    fake.HTML = _FakeHTML
    monkeypatch.setitem(sys.modules, "weasyprint", fake)
    return captured


def _html(client, org, monkeypatch, **params) -> str:
    captured = _stub_renderer(monkeypatch)
    r = client.post("/v1/passport", headers=org["auth"], params=params)
    assert r.status_code == 200, r.text
    assert r.headers["content-type"] == "application/pdf"
    return captured["html"]


# ══ §12.1 · branding ═══════════════════════════════════════════════════════

def test_the_document_is_branded(make_org, client, monkeypatch):
    org = make_org()
    _ingest(client, org, 3)
    doc = _html(client, org, monkeypatch)
    assert "Foxy Audit" in doc
    assert 'class="wordmark"' in doc
    assert "Content-blind audit evidence" in doc
    # The mark is the REAL Foxy logo, embedded as base64 — not a hand-drawn
    # stand-in and not a network fetch (CSP + weasyprint renders offline).
    # An auditor comparing this against the website must see the same fox.
    assert 'class="brand-mark"' in doc
    assert "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAQAAAAEA" in doc, (
        "the brand mark is no longer the shipped logo — a passport that carries "
        "a different mark than the product is worse than one carrying none")
    assert "http://" not in doc.split("<style>")[0]


def test_no_emoji_survived_anywhere(make_org, client, monkeypatch):
    """The old header led with a fox emoji. Nothing says "not a real company
    document" faster, and it is the one thing the owner would notice first."""
    org = make_org()
    _ingest(client, org, 2)
    doc = _html(client, org, monkeypatch)
    emoji = [ch for ch in doc if ord(ch) > 0x2500 and ch not in "─═·—–‖ₙ₋₁“”’"]
    assert not emoji, f"emoji or stray pictographs in the document: {set(emoji)}"


# ══ §12.2 · issued-by block ════════════════════════════════════════════════

def test_the_issued_by_block_answers_who_what_when(make_org, client, monkeypatch):
    org = make_org()
    _ingest(client, org, 4)
    doc = _html(client, org, monkeypatch, days=30)
    for label in ("Issued to", "Workspace ID", "Period covered",
                  "Generated at", "Generated by", "Document reference"):
        assert label in doc, f"the issued-by block is missing '{label}'"
    assert org["org_id"] in doc


def test_generated_by_names_the_key_when_a_machine_asked(make_org, client, monkeypatch):
    org = make_org()
    _ingest(client, org, 2)
    assert "API key (SDK)" in _html(client, org, monkeypatch)


def test_generated_by_names_the_person_when_a_person_asked(make_org, login, client,
                                                           monkeypatch):
    """A named requester is the first thing an auditor asks about a report."""
    org = make_org()
    _ingest(client, org, 2)
    captured = _stub_renderer(monkeypatch)
    c = login(org["admin_email"], org["admin_password"])
    r = c.post("/v1/passport")
    assert r.status_code == 200, r.text
    doc = captured["html"]
    assert org["admin_email"] in doc
    assert "API key (SDK)" not in doc


# ══ §12.6 · determinism — the rule that matters ════════════════════════════

def test_the_document_reference_is_derived_not_random(make_org, client, monkeypatch):
    """Same period over the same chain is the same document, so two copies can be
    compared by reference instead of by eye."""
    org = make_org()
    _ingest(client, org, 5)
    a = _html(client, org, monkeypatch, days=30)
    b = _html(client, org, monkeypatch, days=30)
    ref = re.compile(r"FA-[0-9A-F]{12}")
    ids_a, ids_b = set(ref.findall(a)), set(ref.findall(b))
    assert ids_a and ids_a == ids_b, "the reference changed between identical renders"


def test_the_reference_changes_when_the_evidence_changes(make_org, client, monkeypatch):
    org = make_org()
    _ingest(client, org, 3)
    before = set(re.findall(r"FA-[0-9A-F]{12}", _html(client, org, monkeypatch)))
    _ingest(client, org, 2)              # the chain moved on
    after = set(re.findall(r"FA-[0-9A-F]{12}", _html(client, org, monkeypatch)))
    assert before != after, "the reference ignored a change to the underlying chain"


def test_every_headline_figure_matches_a_counter(make_org, client, monkeypatch):
    """No estimate, no rounding for looks. 7 events in, 7 events reported."""
    org = make_org()
    _ingest(client, org, 7)
    doc = _html(client, org, monkeypatch)
    figures = re.findall(r'<div class="v">([^<]+)</div>', doc)
    assert figures[:3] == ["7", "7", "0"], figures
    assert figures[3] == "100.0%"


def test_an_empty_period_is_honest_rather_than_flattering(make_org, client, monkeypatch):
    """Zero events must not render as a clean bill of health."""
    org = make_org()
    doc = _html(client, org, monkeypatch)
    # The state used to live inside the seal's own SVG rings; it now sits in the
    # .seal-facts block beside the image, which is the only place a reader can
    # still get it without opening the body.
    assert ">NO EVENTS<" in _seal_facts(doc)
    flat = _flat(doc)
    assert "No audit events were captured in the selected report period." in flat
    assert "read it with the total beside it" in flat, \
        "a 100% rate over zero events needs the caveat next to it"


def test_no_prompt_or_response_text_reaches_the_document(make_org, client, monkeypatch):
    """Content-blindness holds in the artefact the customer hands out."""
    org = make_org()
    _ingest(client, org, 3)
    doc = _html(client, org, monkeypatch)
    for forbidden in ("prompt_text", "response_text", "password_hash",
                      "key_hash", "token_hash", "_key_enc"):
        assert forbidden not in doc


def _break_the_chain(client, org, monkeypatch):
    """Corrupt one stored chain_hash so passport.py's recompute disagrees with it.

    There is no API that produces this state — that is the whole point of a
    tamper-evident chain — so the only way to see the failed seal is to reach
    past the app and edit the row, exactly as an attacker with database access
    would. Editing the LAST row keeps the break inside the report period."""
    db = SessionLocal()
    try:
        db.execute(text(
            "UPDATE audit_logs SET chain_hash = :h "
            "WHERE org_id = :o AND seq = (SELECT MAX(seq) FROM audit_logs WHERE org_id = :o)"
        ), {"h": "0" * 64, "o": uuid.UUID(org["org_id"])})
        db.commit()
    finally:
        db.close()


def _template() -> str:
    """The Jinja source itself, for the assertions that are about which image
    each branch selects rather than about one rendered document."""
    return (Path(__file__).resolve().parents[2]
            / "app" / "templates" / "compliance_passport.html").read_text(encoding="utf-8")


def _seal_facts(doc: str) -> str:
    """The block beside the seal image — state, sequence range, as-of date.
    Sliced to INCLUDE the closing tag of the last line, so assertions can anchor
    on `>value<` and cannot pass on a truncated match."""
    i = doc.index('class="seal-facts"')
    j = doc.index("</div>", doc.index('class="seal-asof"')) + len("</div>")
    return doc[i:j]


def _seal_image(doc: str) -> str:
    """Which of the three prepared seals the template chose, by matching the
    rendered <img src> back to the branch that set it."""
    m = re.search(r'<img class="seal"[^>]*src="(data:image/png;base64,[^"]+)"', doc)
    assert m, "the seal image is gone from the cover"
    src = m.group(1)
    tpl = _template()
    for state in ("verified", "failed", "noevents"):
        branch = {"verified": 'seal_col = "#107435"',
                  "failed": 'seal_col = "#c42020"',
                  "noevents": 'seal_col = "#8c5a06"'}[state]
        seg = tpl[tpl.index(branch):]
        if src in seg[:seg.index("{%", seg.index("seal_src"))]:
            return state
    raise AssertionError("the rendered seal matches none of the three branches")


# ══ §12.3 · the seal ═══════════════════════════════════════════════════════
#
# The seal is now a struck IMAGE plus a facts block, not one SVG carrying both.
# That split is the thing to guard: the image is a maker's mark that says only
# "FOXY AUDIT · SINCE 2026", so if the facts block were ever dropped the cover
# would look MORE authoritative while saying strictly less. Every test below
# checks the pair, never just "a seal exists".


def test_the_seal_reports_the_chain_result(make_org, client, monkeypatch):
    org = make_org()
    _ingest(client, org, 4)
    doc = _html(client, org, monkeypatch)
    assert 'class="seal"' in doc
    facts = _seal_facts(doc)
    assert ">CHAIN VERIFIED<" in facts
    assert "#107435" in facts                    # the ok green, on a verified chain
    assert _seal_image(doc) == "verified", "a verified chain must carry the struck gold"


def test_the_facts_beside_the_seal_survive(make_org, client, monkeypatch):
    """State, scope and as-of date. The image says none of these — it is brand,
    not evidence — so losing this block would leave a passport whose reader
    cannot tell WHAT was checked or over WHICH records."""
    org = make_org()
    _ingest(client, org, 6)
    doc = _html(client, org, monkeypatch)
    facts = _seal_facts(doc)
    assert ">CHAIN VERIFIED<" in facts, "the state word is gone from the cover"
    m = re.search(r'class="seal-scope">SEQ (\d+)[–-](\d+)<', facts)
    assert m, "the sequence range is gone from the cover"
    assert int(m.group(2)) >= int(m.group(1))
    assert re.search(r'class="seal-asof">\d{4}-\d{2}-\d{2}<', facts),         "the as-of date is gone from the cover"


@pytest.mark.parametrize("state,expect_word", [
    ("failed", "CHAIN BROKEN"),
    ("noevents", "NO EVENTS"),
])
def test_gold_never_renders_on_an_unverified_chain(make_org, client, monkeypatch,
                                                   state, expect_word):
    """THE RULE THIS WHOLE PHASE PRESERVES. The gold seal is photographic and can
    only ever mean one thing; the other two states get the unstruck line art. A
    gold strike on a broken chain would be the document lying in the one place a
    reader trusts at a glance."""
    org = make_org()
    if state == "failed":
        _ingest(client, org, 3)
        _break_the_chain(client, org, monkeypatch)
    doc = _html(client, org, monkeypatch)

    assert _seal_image(doc) != "verified", f"a {state} chain was struck in gold"
    assert _seal_image(doc) == state
    facts = _seal_facts(doc)
    assert f">{expect_word}<" in facts
    assert "#107435" not in facts, "an unverified period got the verified colour"


def test_the_three_seals_are_three_distinct_images():
    """One tinted image cannot serve all three states — the gold is a rendered
    metal strike, not flat art. If two branches ever pointed at the same blob,
    two different chain results would look identical on the cover."""
    srcs = re.findall(r'set seal_src = "(data:image/png;base64,[^"]+)"', _template())
    assert len(srcs) == 3, f"expected three seal images, found {len(srcs)}"
    assert len(set(srcs)) == 3, "two chain states share a seal image"
    for src in srcs:
        blob = base64.b64decode(src.split(",", 1)[1], validate=True)
        # PNG magic as hex, not an escaped byte literal — the escapes in
        # b"\x89PNG\r\n\x1a\n" are exactly the kind of thing a shell eats.
        assert blob.startswith(bytes.fromhex("89504e470d0a1a0a")), \
            "a seal src is not a real PNG"
        assert len(blob) > 4096, "a seal image decodes to almost nothing"


def test_the_seal_does_not_claim_regulatory_compliance(make_org, client, monkeypatch):
    """The seal attests one narrow fact. Overclaiming here is the difference
    between evidence and marketing."""
    org = make_org()
    _ingest(client, org, 2)
    doc = _html(client, org, monkeypatch)
    assert "not a certification of regulatory compliance" in _flat(doc)


# ══ §12.4 · independent verification ═══════════════════════════════════════

def test_the_document_says_how_to_check_it_without_us(make_org, client, monkeypatch):
    """The document's central claim: a third party can check it without us.

    This asserted the literal string "foxy_verify.py" until the invocation line
    was removed. The route it was standing in for is the STEP, not the command —
    recomputing the chain from an export is the only thing here that turns records
    into a root hash to compare, and §Trust model (which carried the chain formula)
    is gone, so nothing else can stand in for it. Asserted on the step's substance
    so the command can come and go without this test going quiet.
    """
    org = make_org()
    _ingest(client, org, 3)
    doc = _html(client, org, monkeypatch)
    flat = _flat(doc)
    assert "How to verify this independently" in doc
    assert "standalone verifier" in flat, \
        "the recomputation step is gone — nothing left produces the root hash " \
        "that step 3 tells the reader to compare"
    assert "no dependencies" in flat and "no network calls" in flat, \
        "the verifier's independence is the reason the step counts as a check " \
        "that does not require trusting us"
    assert "Root chain hash" in doc
    assert "Genesis hash" in doc
    # The root hash is the thing being verified, so it must actually be printed.
    assert re.search(r'<div class="hash">[0-9a-f]{64}</div>', doc)


def test_no_verification_url_is_invented(make_org, client, monkeypatch):
    """The org has published no badge token and has no confirmed anchor, so there
    is no public URL that would work. Printing one that 404s is worse than
    printing none."""
    org = make_org()
    _ingest(client, org, 2)
    doc = _html(client, org, monkeypatch)
    body = doc.split("<body>", 1)[1]
    assert "/verify/" not in body
    assert "etherscan.io" not in body
    assert "the strongest available check is" in _flat(body)
    # An absent value must be absent, not rendered as the string "None". A stray
    # "None" in an evidence document is the same class of defect as a dead link.
    assert "None" not in body


def test_the_public_status_url_appears_once_the_org_publishes_one(make_org, client,
                                                                  monkeypatch):
    from app.db import SessionLocal
    from app.models import Organization
    org = make_org()
    _ingest(client, org, 2)
    with SessionLocal() as db:
        db.get(Organization, uuid.UUID(org["org_id"])).public_badge_token = "tok_abc123"
        db.commit()
    doc = _html(client, org, monkeypatch)
    assert "/verify/tok_abc123" in doc


# ══ §12.5 · pagination, and the HTML branch that cannot have it ════════════

def test_the_pdf_branch_gets_page_numbers(make_org, client, monkeypatch):
    org = make_org()
    _ingest(client, org, 2)
    doc = _html(client, org, monkeypatch)
    assert "@bottom-right" in doc
    assert 'counter(page)' in doc and 'counter(pages)' in doc
    assert "@page :first" in doc, "the cover must not repeat the running header"


def test_the_html_branch_never_shows_an_empty_page_counter(make_org, client, monkeypatch):
    """Trap 2. The counter lives in a @page margin box, which HTML ignores — so
    the HTML must not render a stranded 'Page  of ' anywhere in its body."""
    org = make_org()
    _ingest(client, org, 2)
    body = _html(client, org, monkeypatch).split("</style>", 1)[1]
    assert "Page " not in body
    assert "counter(" not in body


def test_the_html_branch_explains_itself_instead(make_org, client, monkeypatch):
    org = make_org()
    _ingest(client, org, 2)
    doc = _html(client, org, monkeypatch)
    # The exact tag, not just the words: a malformed or hidden variant would keep
    # the strings while showing the reader nothing.
    assert '<div class="screen-note screen-only">' in doc
    assert "Web rendering." in _flat(doc)
    assert re.search(r'\{\{ document_id \}\}|FA-[0-9A-F]{12}', doc)
    # ...and that explanation must never appear on paper.
    assert re.search(r"@media print\{\s*\.screen-only\{display:none;\}\s*\}", doc)


def test_the_cover_is_a_cover(make_org, client, monkeypatch):
    org = make_org()
    _ingest(client, org, 2)
    doc = _html(client, org, monkeypatch)
    assert 'class="cover"' in doc
    assert "page-break-after:always" in doc
    assert "Compliance<br>Passport" in doc


# ══ the document is complete, and the route is a PDF or an error ════════════

def test_the_rendered_document_is_complete(make_org, client, monkeypatch):
    """Every section reaches the renderer. This used to be asserted against the
    HTML degrade's response body; the degrade is gone, so it is asserted against
    what the renderer is actually handed."""
    org = make_org()
    _ingest(client, org, 5)
    doc = _html(client, org, monkeypatch)
    assert doc.strip().startswith("<!DOCTYPE html>")
    assert doc.strip().endswith("</html>")
    for section in ("Audit summary", "Host-Side Enforcement", "SDK Capture Coverage",
                    "Policy breakdown", "Verification record",
                    "How to verify this independently"):
        assert section in doc, f"the document dropped '{section}'"
    # §Trust model was removed on the owner's instruction; asserted absent so a
    # revert cannot quietly restore it without this list being reconsidered.
    # Matched on the HEADING, not the bare phrase — a CSS comment in the template
    # explains why the section went, and a substring test reads that explanation
    # as the section itself. Same trap that bit the P6b and P6d guards.
    assert "Trust model</h2>" not in doc


def test_the_response_is_a_pdf_built_from_that_document(make_org, client, monkeypatch):
    """The wire contract: application/pdf, a download filename, and the bytes
    built from exactly the html asserted everywhere else in this file."""
    captured = _stub_renderer(monkeypatch)
    org = make_org()
    _ingest(client, org, 3)
    r = client.post("/v1/passport", headers=org["auth"])
    assert r.status_code == 200
    assert r.headers["content-type"] == "application/pdf"
    assert "attachment; filename=passport.pdf" in r.headers.get("content-disposition", "")
    assert r.content.startswith(b"%PDF-")
    doc = captured["html"]
    assert doc.strip().startswith("<!DOCTYPE html>")
    assert "Compliance<br>Passport" in doc
    assert "@bottom-right" in doc
    assert re.search(r"FA-[0-9A-F]{12}", doc)


def test_an_empty_org_renders_rather_than_reading_as_broken(make_org, client,
                                                           monkeypatch):
    """An org with no events at all is the edge that used to look like a fault."""
    _stub_renderer(monkeypatch)
    org = make_org()
    r = client.post("/v1/passport", headers=org["auth"])
    assert r.status_code == 200
    assert b"Traceback" not in r.content


def test_a_failed_render_leaks_neither_a_traceback_nor_the_document(make_org, client,
                                                                   monkeypatch):
    """The replacement for the old "html branch" case. A renderer that raises must
    produce a 500 that carries no traceback, no library paths, and NOT the
    document it could not render — the whole reason the degrade was removed."""
    fake = type(sys)("weasyprint")

    class _Boom:
        def __init__(self, string=None, **kw):
            raise OSError("cannot load library 'libgobject-2.0-0': /usr/lib/secret")

    fake.HTML = _Boom
    monkeypatch.setitem(sys.modules, "weasyprint", fake)

    org = make_org()
    r = client.post("/v1/passport", headers=org["auth"])
    assert r.status_code == 500
    assert b"Traceback" not in r.content
    assert b"libgobject" not in r.content, "the renderer's message reached the caller"
    assert b"/usr/lib/secret" not in r.content
    assert b"Compliance" not in r.content, "a failed render must not ship the document"
